//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/friend.proto
namespace protos.friend
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRemoveFriend")]
  public partial class ReqRemoveFriend : global::ProtoBuf.IExtensible
  {
    public ReqRemoveFriend() {}
    
    private int _feiendId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feiendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feiendId
    {
      get { return _feiendId; }
      set { _feiendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGiveVigor")]
  public partial class ReqGiveVigor : global::ProtoBuf.IExtensible
  {
    public ReqGiveVigor() {}
    
    private int _feiendId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feiendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feiendId
    {
      get { return _feiendId; }
      set { _feiendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetFriendList")]
  public partial class ReqGetFriendList : global::ProtoBuf.IExtensible
  {
    public ReqGetFriendList() {}
    
    private int _feiendId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feiendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feiendId
    {
      get { return _feiendId; }
      set { _feiendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResFriendList")]
  public partial class ResFriendList : global::ProtoBuf.IExtensible
  {
    public ResFriendList() {}
    
    private readonly global::System.Collections.Generic.List<UserInfo> _userInfo = new global::System.Collections.Generic.List<UserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UserInfo> userInfo
    {
      get { return _userInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAddFriend")]
  public partial class ReqAddFriend : global::ProtoBuf.IExtensible
  {
    public ReqAddFriend() {}
    
    private int _feiendId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feiendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feiendId
    {
      get { return _feiendId; }
      set { _feiendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _uid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _lv = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private string _head = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _is_give = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"is_give", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_give
    {
      get { return _is_give; }
      set { _is_give = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqFindFriend")]
  public partial class ReqFindFriend : global::ProtoBuf.IExtensible
  {
    public ReqFindFriend() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _pageSize = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResFindFriendList")]
  public partial class ResFindFriendList : global::ProtoBuf.IExtensible
  {
    public ResFindFriendList() {}
    
    private readonly global::System.Collections.Generic.List<UserInfo> _userInfo = new global::System.Collections.Generic.List<UserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UserInfo> userInfo
    {
      get { return _userInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDeleteFriend")]
  public partial class ReqDeleteFriend : global::ProtoBuf.IExtensible
  {
    public ReqDeleteFriend() {}
    
    private int _feiendId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feiendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feiendId
    {
      get { return _feiendId; }
      set { _feiendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}