//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/info.proto
namespace protos.info
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorInfo")]
  public partial class ErrorInfo : global::ProtoBuf.IExtensible
  {
    public ErrorInfo() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private string _details = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string details
    {
      get { return _details; }
      set { _details = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorTest")]
  public partial class ErrorTest : global::ProtoBuf.IExtensible
  {
    public ErrorTest() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private string _details = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string details
    {
      get { return _details; }
      set { _details = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _userInfo = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> userInfo
    {
      get { return _userInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}